import React from 'react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Simple Header */}
      <div className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 py-6">
          <div className="flex items-center justify-between">
            <div>
              <Link to="/" className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-3">
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Back to Home
              </Link>
              <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
              <p className="text-gray-600 mt-1">Last updated: {new Date().toLocaleDateString('en-IN')}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-4 py-8">
        <div className="bg-white rounded-lg shadow-sm p-6">
          
          {/* Introduction */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">1. Introduction</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                These Terms of Service ("Terms") constitute a legally binding agreement between
                ExpertSetu LLP, a limited liability partnership registered under the Limited Liability
                Partnership Act, 2008 (hereinafter referred to as "ExpertSetu", "the Company", "we",
                "our", or "us") and any natural or legal person ("User", "you", or "your") who accesses,
                registers for, or uses our website, platform, mobile applications, and all related
                software, features, and services offered by ExpertSetu (collectively, the "Services").
              </p>
              <p className="mb-4 text-gray-700 leading-relaxed">
                By accessing or using the Services, you agree to comply with and be bound by these
                Terms, our Privacy Policy, Cookie Policy, and Refund Policy (collectively, "Agreements").
                If you do not agree to any of these, you must not access or use our Services.
              </p>
            </div>
          </section>

          {/* Eligibility */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">2. Eligibility</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                You represent that you are at least 18 years of age and capable of entering into a legally
                binding contract as per the Indian Contract Act, 1872. If you are using the Services on
                behalf of a business or legal entity, you represent that you have the authority to bind that
                entity to these Terms.
              </p>
            </div>
          </section>

          {/* Scope of Services */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">3. Scope of Services</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                ExpertSetu operates an AI-powered legal assistance platform that provides users with
                automated research support, legal documentation assistance, and knowledge insights.
                The Services are intended to assist users in understanding legal topics but do not
                constitute legal advice.
              </p>
              <div className="bg-yellow-50 border-l-4 border-yellow-500 p-4 rounded">
                <p className="font-medium text-gray-800 mb-2">You acknowledge and agree that:</p>
                <ul className="list-disc pl-6 text-gray-700 space-y-1">
                  <li>Outputs generated by the AI system are for informational purposes only.</li>
                  <li>ExpertSetu is not a law firm and does not provide legal representation.</li>
                  <li>You are solely responsible for verifying the accuracy, reliability, and applicability of any content generated by the platform.</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Account Registration */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">4. Account Registration and Access</h2>
            <div className="prose max-w-none">
              <div className="space-y-3">
                <div className="flex items-start p-3 bg-blue-50 rounded">
                  <span className="w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">1</span>
                  <span className="text-gray-700">To access certain features, users may be required to create an account by providing accurate and complete information.</span>
                </div>
                <div className="flex items-start p-3 bg-blue-50 rounded">
                  <span className="w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">2</span>
                  <span className="text-gray-700">You agree to maintain the confidentiality of your account credentials and are solely responsible for all activities occurring under your account.</span>
                </div>
                <div className="flex items-start p-3 bg-blue-50 rounded">
                  <span className="w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">3</span>
                  <span className="text-gray-700">ExpertSetu reserves the right to suspend, disable, or terminate accounts suspected of unauthorized access, misuse, or violation of these Terms.</span>
                </div>
              </div>
            </div>
          </section>

          {/* Acceptable Use Policy */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">5. Acceptable Use Policy</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700">Users agree not to:</p>
              <div className="bg-red-50 border-l-4 border-red-500 p-4 rounded">
                <ul className="list-disc pl-6 text-gray-700 space-y-2">
                  <li>Use the Services for any unlawful, fraudulent, or malicious purpose.</li>
                  <li>Upload or transmit any harmful, defamatory, or infringing content.</li>
                  <li>Attempt to reverse-engineer, decompile, or copy the platform's software or AI algorithms.</li>
                  <li>Interfere with system integrity or security.</li>
                  <li>Use automated systems (bots, scrapers) without prior written consent.</li>
                </ul>
                <p className="mt-3 text-red-700 font-medium">
                  Violation of this clause may lead to immediate termination and potential legal action.
                </p>
              </div>
            </div>
          </section>

          {/* Intellectual Property */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">6. Intellectual Property Rights</h2>
            <div className="prose max-w-none">
              <div className="space-y-3">
                <div className="flex items-start p-3 bg-green-50 rounded">
                  <span className="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">1</span>
                  <span className="text-gray-700">All intellectual property rights, including but not limited to source code, algorithms, text, graphics, designs, interfaces, and trademarks, are the sole property of ExpertSetu LLP.</span>
                </div>
                <div className="flex items-start p-3 bg-green-50 rounded">
                  <span className="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">2</span>
                  <span className="text-gray-700">Nothing in these Terms shall grant you ownership or rights other than the limited license to use the Services for lawful purposes.</span>
                </div>
                <div className="flex items-start p-3 bg-green-50 rounded">
                  <span className="w-6 h-6 bg-green-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">3</span>
                  <span className="text-gray-700">Users may not copy, modify, distribute, or create derivative works based on any part of the platform without prior written consent.</span>
                </div>
              </div>
            </div>
          </section>

          {/* Subscriptions and Payments */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">7. Subscriptions, Payments, and Billing</h2>
            <div className="prose max-w-none">
              <div className="space-y-3">
                <div className="flex items-start p-3 bg-purple-50 rounded">
                  <span className="w-6 h-6 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">1</span>
                  <span className="text-gray-700">Certain Services are available through paid subscriptions. Payment details will be clearly communicated before purchase.</span>
                </div>
                <div className="flex items-start p-3 bg-purple-50 rounded">
                  <span className="w-6 h-6 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">2</span>
                  <span className="text-gray-700">All payments shall be processed securely through authorized payment gateways in compliance with the Reserve Bank of India (RBI) regulations.</span>
                </div>
                <div className="flex items-start p-3 bg-purple-50 rounded">
                  <span className="w-6 h-6 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">3</span>
                  <span className="text-gray-700">By subscribing, you authorize ExpertSetu to charge the applicable fees to your designated payment method.</span>
                </div>
                <div className="flex items-start p-3 bg-purple-50 rounded">
                  <span className="w-6 h-6 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">4</span>
                  <span className="text-gray-700">All fees are non-refundable, except as expressly provided in our Refund Policy.</span>
                </div>
                <div className="flex items-start p-3 bg-purple-50 rounded">
                  <span className="w-6 h-6 bg-purple-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">5</span>
                  <span className="text-gray-700">ExpertSetu reserves the right to modify pricing or subscription terms with prior notice via email or website announcement.</span>
                </div>
              </div>
            </div>
          </section>

          {/* Data Protection */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">8. Data Protection and Privacy</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                ExpertSetu collects and processes user data in accordance with the Digital Personal
                Data Protection Act, 2023, the Information Technology Act, 2000, and its allied rules.
                Our detailed data-handling practices are provided in the Privacy Policy, which forms an
                integral part of these Terms.
              </p>
            </div>
          </section>

          {/* Disclaimers */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">9. Disclaimers</h2>
            <div className="prose max-w-none">
              <div className="space-y-3">
                <div className="flex items-start p-3 bg-orange-50 rounded">
                  <span className="w-6 h-6 bg-orange-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">1</span>
                  <span className="text-gray-700">The Services and all outputs provided by the AI system are on an "as is" and "as available" basis without warranties of any kind.</span>
                </div>
                <div className="flex items-start p-3 bg-orange-50 rounded">
                  <span className="w-6 h-6 bg-orange-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">2</span>
                  <span className="text-gray-700">ExpertSetu does not guarantee that the information generated will be accurate, up-to-date, or applicable to a particular legal situation.</span>
                </div>
                <div className="flex items-start p-3 bg-orange-50 rounded">
                  <span className="w-6 h-6 bg-orange-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">3</span>
                  <span className="text-gray-700">No content provided through the Services constitutes professional legal advice. Users should consult a qualified advocate for legal matters.</span>
                </div>
              </div>
            </div>
          </section>

          {/* Limitation of Liability */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">10. Limitation of Liability</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700">To the maximum extent permitted by applicable law:</p>
              <div className="bg-gray-50 p-6 rounded-lg">
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full mt-2 mr-3 flex-shrink-0 bg-gray-500"></span>
                    <span className="text-gray-700">ExpertSetu LLP shall not be liable for any indirect, consequential, incidental, or punitive damages arising from or in connection with the use of the Services.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full mt-2 mr-3 flex-shrink-0 bg-gray-500"></span>
                    <span className="text-gray-700">Our total liability in any event shall not exceed the total subscription amount paid by the user in the preceding three (3) months.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="inline-block w-2 h-2 rounded-full mt-2 mr-3 flex-shrink-0 bg-gray-500"></span>
                    <span className="text-gray-700">ExpertSetu shall not be responsible for loss of data, profits, or goodwill resulting from any malfunction, delay, or interruption of the platform.</span>
                  </li>
                </ul>
              </div>
            </div>
          </section>

          {/* Indemnification */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">11. Indemnification</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                You agree to indemnify and hold harmless ExpertSetu LLP, its partners, employees,
                and affiliates against all claims, damages, liabilities, and expenses (including legal fees)
                arising from your breach of these Terms, misuse of the Services, or violation of any law
                or third-party rights.
              </p>
            </div>
          </section>

          {/* Termination */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">12. Termination</h2>
            <div className="prose max-w-none">
              <div className="space-y-3">
                <div className="flex items-start p-3 bg-red-50 rounded">
                  <span className="w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">1</span>
                  <span className="text-gray-700">ExpertSetu reserves the right to terminate or suspend your account and access to the Services at any time for breach of these Terms or misuse of the platform.</span>
                </div>
                <div className="flex items-start p-3 bg-red-50 rounded">
                  <span className="w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center text-sm font-bold mr-3 flex-shrink-0">2</span>
                  <span className="text-gray-700">Upon termination, all rights granted to you under these Terms shall immediately cease.</span>
                </div>
              </div>
            </div>
          </section>

          {/* Governing Law */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">13. Governing Law and Jurisdiction</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                These Terms shall be governed by and construed in accordance with the laws of India.
                All disputes arising hereunder shall be subject to the exclusive jurisdiction of the courts
                located in Ahmedabad, Gujarat.
              </p>
            </div>
          </section>

          {/* Amendments */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">14. Amendments</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                ExpertSetu may revise these Terms periodically. Any material changes will be notified
                via email or a notice on our website. Continued use of the Services constitutes
                acceptance of the revised Terms.
              </p>
            </div>
          </section>

          {/* Contact Information */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-3 border-b border-gray-200 pb-2">15. Contact Information</h2>
            <div className="prose max-w-none">
              <p className="mb-4 text-gray-700 leading-relaxed">
                For questions or concerns regarding these Terms, please contact:
              </p>
              <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-6 rounded-lg border border-blue-200">
                <div className="flex items-center mb-4">
                  <div className="w-12 h-12 bg-blue-500 rounded-full flex items-center justify-center mr-4">
                    <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="text-lg font-bold text-gray-900">ExpertSetu LLP</h3>
                    <p className="text-gray-600">Legal Department</p>
                  </div>
                </div>
                <div className="space-y-2">
                  <p className="text-gray-700">
                    <strong>Email:</strong>{' '}
                    <a 
                      href="mailto:inquiry@salhakar.com" 
                      className="text-blue-600 hover:text-blue-800 underline"
                    >
                      inquiry@salhakar.com
                    </a>
                  </p>
                  <p className="text-gray-700">
                    <strong>Response Time:</strong> Within 48 hours
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Footer */}
          <div className="mt-12 pt-8 border-t border-gray-200 text-center">
            <p className="text-sm text-gray-500">
              These Terms of Service are effective as of the date of last update and apply to all users of our Services.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
